// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGg0Sc8oaAijrpe5LN68JX5fZjV9Y9CcU',
    appId: '1:1070442560483:web:d83f135b1628d495b1bed6',
    messagingSenderId: '1070442560483',
    projectId: 'golden-wave',
    authDomain: 'golden-wave.firebaseapp.com',
    storageBucket: 'golden-wave.appspot.com',
    measurementId: 'G-65Q45KZ9K1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqI8nYLUp6gb7SdBd3IKE2wrvMAMuF1dM',
    appId: '1:1070442560483:android:52d5c59ceb1d4580b1bed6',
    messagingSenderId: '1070442560483',
    projectId: 'golden-wave',
    storageBucket: 'golden-wave.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUEqO0RLvtXqwmyCYkmRSTfTl_6b9oFXs',
    appId: '1:1070442560483:ios:71b0f33c2ce22519b1bed6',
    messagingSenderId: '1070442560483',
    projectId: 'golden-wave',
    storageBucket: 'golden-wave.appspot.com',
    iosBundleId: 'com.example.goldenWave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUEqO0RLvtXqwmyCYkmRSTfTl_6b9oFXs',
    appId: '1:1070442560483:ios:71b0f33c2ce22519b1bed6',
    messagingSenderId: '1070442560483',
    projectId: 'golden-wave',
    storageBucket: 'golden-wave.appspot.com',
    iosBundleId: 'com.example.goldenWave',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGg0Sc8oaAijrpe5LN68JX5fZjV9Y9CcU',
    appId: '1:1070442560483:web:0335456a634cbfdab1bed6',
    messagingSenderId: '1070442560483',
    projectId: 'golden-wave',
    authDomain: 'golden-wave.firebaseapp.com',
    storageBucket: 'golden-wave.appspot.com',
    measurementId: 'G-XB8YYWWFG3',
  );
}
